### ISSUE TITLE
Unwanted permissions added by manifest merger because targetSdkVersion is not definied in cwac-endless library

### ISSUE THREAD

**Issue by shubhambansal** [commonsguy/cwac-merge#18]
Hi,

We are using cwac-endless library in our application and noticed that APK built with Android Studio/Gradle has more permissions than we declared in our AndroidManifest.xml.

In "...\build\outputs\apk" manifest merger generates files (manifest-merger-[debug|release]-report.txt) with information why and from each element was added to the final manifest. In these files you can see something like below:

android:uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from AndroidManifest.xml:2:1 reason: com.commonsware.cwac.endless has a targetSdkVersion < 4

which is true because CWAC's manifest doesn't specify minSdkVersion or targetSdkVersion so both defaults to 1.

Steps to reproduce:
1. Using latest Android Studio (1.0.0-rc4) create simple project with empty Activity.
2. Add dependency: compile 'com.commonsware.cwac:endless:1.2.3
3. Build project: gradlew build
4. Go to "...\build\outputs\apk" and check manifest-merger-[debug|release]-report.txt or examine final APK files using tools like ApkTool.

It would great if you can specify some minimal targetSdkVersion like "4" to prevent manifest merger from automatically adding permissions which have nothing in common with MergeAdapter :)

Thanks.
Shubham Bansal
Zalando

**Comment by commonsguy** [comment]
> We are using cwac-endless library in our application

First, this is not the repository for `cwac-endless`. This is the repository for `cwac-merge`.

Second, `cwac-endless` was discontinued, and I recommend that you stop using it. I certainly am not making any more changes to it.

Now, this *also* happens to be an issue with `cwac-merge`, and I will eventually address it. In the meantime, modify your app's `<uses-sdk>` element to include the `tools:ignoreLibrary` attribute:

```xml
<uses-sdk android:targetSdkVersion="..." android:minSdkVersion="..."
    tools:overrideLibrary="com.commonsware.cwac.merge"/>
```

(replacing the two `...` values with appropriate API levels for your app)

**Comment by shubhambansal** [comment]
Thanks for you reply.

And, Sorry for posting this bug on wrong repository.


Thanks !!
Shubham

**Comment by commonsguy** [comment]
Well, I cannot reproduce your problem with this library. If I do a clean build of `cwac-merge`'s `demo/` project, the resulting APK has a `targetSdkVersion` of 14, which is what the `demo/` project has in its manifest. This comes despite the fact that neither `cwac-merge` nor `cwac-sacklist` (a transitive dependency) specify a `targetSdkVersion` in their manifests or `build.gradle` files. Similarly, my manifest merger report, and the **`aapt dump badging`** output, do not show any added permissions due to low `targetSdkVersion` values.

With respect to `cwac-endless`, again, that project has been discontinued. I have the bits out there for historical reasons, but I do not recommend that anyone use it, and I am no longer maintaining it.

BTW, the latest Android Studio is 1.0.2, not 1.0.0-rc4.

**Comment by shubhambansal** [comment]
The problem is not with cwac-merge library. The problem is coming with cwac-endless (which you are not supporting anymore).

**Comment by commonsguy** [comment]
@shubhambansal Since `cwac-endless` is configured the same way as `cwac-merge` and `cwac-sacklist`, I fail to see how the problem would recur there. Make sure that you are on the latest `buildToolsVersion`, and fall back to the `tools:overrideLibrary` attribute mentioned above if needed.

**Comment by shubhambansal** [comment]
I am getting following logs from manifest-merger-debug-report.txt file. 

android:uses-permission#android.permission.READ_PHONE_STATE
IMPLIED from AndroidManifest.xml:2:1 reason: com.commonsware.cwac.endless has a targetSdkVersion < 4
